apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: budget-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: budget-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization