apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: budgetacr.azurecr.io/userintelij:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: SYMFONY_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                    name: mysql-configmap
                    key: connection_string
          resources:
            requests:
              memory: "128Mi"  # Adjusted
              cpu: "0.2"       # Adjusted
            limits:
              memory: "256Mi"  # Adjusted
              cpu: "0.5"       # Adjusted
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005